{% set name = "pymssql" %}
{% set version = "2.1.4" %}
{% set sha256 = "3201eb1b1263ad55b555d727ed8bed0b12b7b9de3ce5e529206e36d4be1a7afb" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  # git_url: https://github.com/pymssql/pymssql.git
  # git_rev: cc5676fb8887e7233c8de9121b2b71832991d606 

build:
  number: 2001
  skip: true  # [win]
  script:
    - python setup.py build_ext --include-dirs=%PREFIX%\include --library-dirs=%PREFIX%\lib  # [win]
    - python setup.py build_ext --include-dirs=$PREFIX/include --library-dirs=$PREFIX/lib    # [not win]
    - python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools
    - cython
    - freetds
    - setuptools-git
  run:
    - python
    - freetds

test:
    imports:
        - pymssql
about:
    dev_url: https://github.com/pymssql/pymssql
    doc_url: http://www.pymssql.org/en/stable/
    home: http://pymssql.org
    license: LGPL
    license_family: LGPL
    license_file: LICENSE
    summary: DB-API interface to Microsoft SQL Server for Python. (new Cython-based version)

extra:
  recipe-maintainers:
    - mariusvniekerk
